"""状态字符串常量集中定义。

设计选择：使用 TEXT 列 + Python 常量类，而非 PostgreSQL ENUM 类型。

理由：
1. 新增状态时只需改 Python 常量，无需 ``ALTER TYPE`` 迁移；
2. ``reason_codes`` / ``event_type`` 等天然就是字符串数组 / 字符串，不适合 ENUM；
3. 测试与 fixture 直接用字符串字面量更直观。

约束由应用层的 ``validate_transition``（任务 2.3）+ Pydantic schemas（后续任务）共同把守。

对应：design.md「状态机转换表」 / PRD §7（PassportState、ActionState、CredentialState） / PRD §14（AuditEventType）。
"""

from __future__ import annotations


class PassportState:
    """Passport 生命周期状态（design.md PASSPORT_TRANSITIONS）。

    DRAFT → ACTIVE / DELETED
    ACTIVE → PAUSED / REVOKED / EXPIRED
    PAUSED → ACTIVE / REVOKED
    REVOKED / EXPIRED / DELETED → 终态
    """

    DRAFT = "DRAFT"
    ACTIVE = "ACTIVE"
    PAUSED = "PAUSED"
    REVOKED = "REVOKED"
    EXPIRED = "EXPIRED"
    DELETED = "DELETED"

    ALL: frozenset[str] = frozenset({DRAFT, ACTIVE, PAUSED, REVOKED, EXPIRED, DELETED})


class ActionState:
    """Action 状态机（design.md ACTION_TRANSITIONS / PRD §7.2）。

    主要路径：
        REQUESTED → PLANNING → PLAN_VALIDATED → RISK_CHECKING
                  → APPROVAL_REQUIRED → APPROVED → EXECUTING → EXECUTED
    分支：
        AUTO_APPROVED（只读类）→ EXECUTING → EXECUTED
        AUTO_REJECTED / REJECTED_BY_USER / EXPIRED / FAILED / CANCELLED → 终态
    """

    REQUESTED = "REQUESTED"
    PLANNING = "PLANNING"
    PLAN_VALIDATED = "PLAN_VALIDATED"
    PLAN_INVALID = "PLAN_INVALID"
    RISK_CHECKING = "RISK_CHECKING"
    APPROVAL_REQUIRED = "APPROVAL_REQUIRED"
    AUTO_APPROVED = "AUTO_APPROVED"
    APPROVED = "APPROVED"
    REJECTED_BY_USER = "REJECTED_BY_USER"
    AUTO_REJECTED = "AUTO_REJECTED"
    EXPIRED = "EXPIRED"
    EXECUTING = "EXECUTING"
    EXECUTED = "EXECUTED"
    EXECUTION_FAILED = "EXECUTION_FAILED"
    FAILED = "FAILED"
    CANCELLED = "CANCELLED"

    ALL: frozenset[str] = frozenset({
        REQUESTED, PLANNING, PLAN_VALIDATED, PLAN_INVALID, RISK_CHECKING,
        APPROVAL_REQUIRED, AUTO_APPROVED, APPROVED, REJECTED_BY_USER,
        AUTO_REJECTED, EXPIRED, EXECUTING, EXECUTED, EXECUTION_FAILED,
        FAILED, CANCELLED,
    })


class CredentialState:
    """API 凭证状态（design.md CREDENTIAL_TRANSITIONS / Req 2）。

    CREATED → VALIDATING → READ_ONLY / TRADE_ENABLED / INVALID
    READ_ONLY / TRADE_ENABLED → VALIDATING / REVOKED / DELETED
    INVALID → VALIDATING / DELETED
    REVOKED / DELETED → 终态
    """

    CREATED = "CREATED"
    VALIDATING = "VALIDATING"
    READ_ONLY = "READ_ONLY"
    TRADE_ENABLED = "TRADE_ENABLED"
    INVALID = "INVALID"
    REVOKED = "REVOKED"
    DELETED = "DELETED"

    ALL: frozenset[str] = frozenset({
        CREATED, VALIDATING, READ_ONLY, TRADE_ENABLED, INVALID, REVOKED, DELETED,
    })


class AuditEventType:
    """审计事件类型（PRD §14 + Req 11 AC6 「覆盖 18 种 audit_event_types」 + design.md 补充）。

    分组：
    - 用户与认证：USER_LOGIN
    - 凭证：CREDENTIAL_CREATED / CREDENTIAL_VALIDATED / CREDENTIAL_DELETED
    - Passport：PASSPORT_CREATED / PASSPORT_POLICY_UPDATED / PASSPORT_PAUSED /
                  PASSPORT_RESUMED / PASSPORT_REVOKED
    - Plan：ACTION_REQUESTED / ACTION_CANCELLED / PLAN_SCHEMA_VALIDATED /
              PLAN_INVALID / PLAN_HALLUCINATION
    - 模型调用：MODEL_CALL_STARTED / MODEL_CALL_COMPLETED / MODEL_CALL_FAILED / MODEL_UNAVAILABLE
    - 策略：POLICY_CHECK_COMPLETED
    - 审批：APPROVAL_REQUESTED / APPROVAL_SUBMITTED / APPROVAL_EXPIRED
    - 执行：EXECUTION_STARTED / EXECUTION_COMPLETED / EXECUTION_FAILED / EXECUTION_BLOCKED_BY_RECHECK
    - 错误恢复：LOOP_DETECTED
    - 反馈：REPUTATION_UPDATED
    """

    # 用户与认证
    USER_LOGIN = "USER_LOGIN"

    # 凭证保险库
    CREDENTIAL_CREATED = "CREDENTIAL_CREATED"
    CREDENTIAL_VALIDATED = "CREDENTIAL_VALIDATED"
    CREDENTIAL_DELETED = "CREDENTIAL_DELETED"

    # Passport 生命周期
    PASSPORT_CREATED = "PASSPORT_CREATED"
    PASSPORT_POLICY_UPDATED = "PASSPORT_POLICY_UPDATED"
    PASSPORT_PAUSED = "PASSPORT_PAUSED"
    # PRD §7.1 PASSPORT_TRANSITIONS 允许 PAUSED → ACTIVE，但 PRD §14 审计事件
    # 列表未显式列出 PASSPORT_RESUMED；这里补齐使该转换有可审计的事件类型，
    # 与 PASSPORT_PAUSED 形成对称。任务 5.3 引入。
    PASSPORT_RESUMED = "PASSPORT_RESUMED"
    PASSPORT_REVOKED = "PASSPORT_REVOKED"

    # Action / Plan
    ACTION_REQUESTED = "ACTION_REQUESTED"
    # 当 passport 被撤销时，下属 APPROVAL_REQUIRED 状态的 action 会级联转 CANCELLED；
    # 任务 13 执行网关在 EXECUTING 中遇到中断也会用此事件类型。任务 5.3 引入。
    ACTION_CANCELLED = "ACTION_CANCELLED"
    PLAN_SCHEMA_VALIDATED = "PLAN_SCHEMA_VALIDATED"
    PLAN_INVALID = "PLAN_INVALID"
    PLAN_HALLUCINATION = "PLAN_HALLUCINATION"

    # 模型调用
    MODEL_CALL_STARTED = "MODEL_CALL_STARTED"
    MODEL_CALL_COMPLETED = "MODEL_CALL_COMPLETED"
    MODEL_CALL_FAILED = "MODEL_CALL_FAILED"
    MODEL_UNAVAILABLE = "MODEL_UNAVAILABLE"

    # 策略裁决
    POLICY_CHECK_COMPLETED = "POLICY_CHECK_COMPLETED"

    # 审批
    APPROVAL_REQUESTED = "APPROVAL_REQUESTED"
    APPROVAL_SUBMITTED = "APPROVAL_SUBMITTED"
    APPROVAL_EXPIRED = "APPROVAL_EXPIRED"

    # 执行
    EXECUTION_STARTED = "EXECUTION_STARTED"
    EXECUTION_COMPLETED = "EXECUTION_COMPLETED"
    EXECUTION_FAILED = "EXECUTION_FAILED"
    EXECUTION_BLOCKED_BY_RECHECK = "EXECUTION_BLOCKED_BY_RECHECK"
    # 审批/执行重裁决时检测到 stale market snapshot 或 limit_price 与
    # 当前 last 价偏差超 max_slippage_bps（修复 G16 / Req 16 AC2）。
    # 写入时 event_data 含 reason_code / snapshot_age_seconds /
    # expected_price / actual_price / deviation_bps / threshold_bps，
    # 便于 audit 重放界面定位"哪一笔在何时被 stale price 拦下"。
    MARKET_SLIPPAGE_DETECTED = "MARKET_SLIPPAGE_DETECTED"

    # 错误恢复
    LOOP_DETECTED = "LOOP_DETECTED"

    # 反馈
    REPUTATION_UPDATED = "REPUTATION_UPDATED"

    ALL: frozenset[str] = frozenset({
        USER_LOGIN,
        CREDENTIAL_CREATED, CREDENTIAL_VALIDATED, CREDENTIAL_DELETED,
        PASSPORT_CREATED, PASSPORT_POLICY_UPDATED, PASSPORT_PAUSED, PASSPORT_RESUMED, PASSPORT_REVOKED,
        ACTION_REQUESTED, ACTION_CANCELLED, PLAN_SCHEMA_VALIDATED, PLAN_INVALID, PLAN_HALLUCINATION,
        MODEL_CALL_STARTED, MODEL_CALL_COMPLETED, MODEL_CALL_FAILED, MODEL_UNAVAILABLE,
        POLICY_CHECK_COMPLETED,
        APPROVAL_REQUESTED, APPROVAL_SUBMITTED, APPROVAL_EXPIRED,
        EXECUTION_STARTED, EXECUTION_COMPLETED, EXECUTION_FAILED, EXECUTION_BLOCKED_BY_RECHECK,
        MARKET_SLIPPAGE_DETECTED,
        LOOP_DETECTED,
        REPUTATION_UPDATED,
    })
